# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Application security testing@2025
  inputs:
    projectName: 'CxSAST_DEmo_test'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'CxSAST'
    sastProxyUrl: 'http://sudhat-lt/'
    enableSastBranching: false
    fullTeamName: 'CxServer'
    incScan: false
    enableDependencyScan: false